### ISSUE TITLE
Exons shorter than k

### ISSUE THREAD

**Issue by sahammond** [bcgsc/ChopStitch#1]
I've observed some cases where the predicted exons for a transcript include ones whose length is shorter than k. Is this expected, and what is their significance? Also, ~10 bases are not included in the predicted exons, missing from between exons 3 and 4. Is this from the leniency factor?

```
>gi|239619018|gb|FJ830670.1|_1_53
ATGTTCACCTTGAAGAAATCCCTGTTGCTCCTTTTCTTTCTTGGGACCATCTC
>gi|239619018|gb|FJ830670.1|_54_73
ATTATCTCTCTGTGAGCAAG
>gi|239619018|gb|FJ830670.1|_74_283
AGAGAGATGCCGATGGAGATGAAGGGGAAGTTGAAGAAGTAAAAAGAGGTTTCCTGGATATCATCAAGGATACGGGGAAGGAATTTGCTGTGAAAATTTTGAATAATTTAAAATGTAAATTGGCTGGAGGATGTCCACCCTGAATCAGAGGTCATCTCATGTGGAATATCACTTAGCTAAATCTGTAATGTCTTATTAAAAAATAAAAAT
>gi|239619018|gb|FJ830670.1|_294_321
AGAAAAAAAAAAAAAAAAAAAAAAAAAA
```

This example is from GenBank. Note that it is 5' incomplete because the PCR primers used by the authors were not designed to capture the 5' UTR; that is, the sequence consists of the CDS and 3' UTR with polyA tail. I built my Bloom filter at k=32.
This is a bullfrog sequence, and alignment to the draft genome indicates that there should be only one exon-exon junction, after the 74th base of the sequence.

**Comment by hamzakhanvit** [comment]
Hi Austin,

As explained in section [2.3.4.](http://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btx839/4781691), putative exons can be less than the _k_-mer size. 

Yes, a difference of around 10 bases is most probably due to the leniency factor. 

An unwanted exon-exon junction might be predicted when there are many sequencing errors or a combination of sequencing error and SNPs  close to each other. How does the alignment between the transcript and draft genome look like? Can you post the CIGAR string?

**Comment by sahammond** [comment]
Hi Hamza,

Thanks for the reminder about section 2.3.4!

The two exons of this transcript align to two separate genomic scaffolds in the draft assembly.
```
74M249H MD:Z:9A43C20
74H219M30S MD:Z:148A70
```
It looks like the second mismatch of the first aligned portion is called as an exon-exon junction, which is noted as a possible scenario in 2.3.4.

**Comment by hamzakhanvit** [comment]
Yes, that might be the case.

**Comment by sahammond** [comment]
OK, I'll be more mindful of this scenario when using non-matched data. Thanks!
